# Generated by Django 5.2.7 on 2025-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, max_length=20, null=True)),
                ('business_name', models.CharField(blank=True, max_length=256, null=True)),
                ('dba_business_name', models.CharField(blank=True, max_length=256, null=True)),
                ('mo_address', models.CharField(blank=True, max_length=256, null=True)),
                ('mo_city', models.CharField(blank=True, max_length=256, null=True)),
                ('mo_state', models.CharField(blank=True, max_length=256, null=True)),
                ('mo_zip', models.CharField(blank=True, max_length=256, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=1, null=True)),
                ('acreage', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('priority_rank', models.IntegerField(blank=True, null=True)),
                ('is_interstate_shipper', models.BooleanField(blank=True, null=True)),
                ('main_contact_name', models.CharField(blank=True, max_length=256, null=True)),
                ('main_contact_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('main_contact_email', models.CharField(blank=True, max_length=256, null=True)),
                ('wants_email_renewal', models.BooleanField(blank=True, null=True)),
                ('wants_email_license', models.BooleanField(blank=True, null=True)),
                ('wants_labels', models.BooleanField(blank=True, null=True)),
                ('num_labels', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'businesses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessPlantTypes',
            fields=[
                ('pk', models.CompositePrimaryKey('business_id', 'plant_type_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'business_plant_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessSellingSeasons',
            fields=[
                ('pk', models.CompositePrimaryKey('business_id', 'season_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'business_selling_seasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessShippingRegions',
            fields=[
                ('pk', models.CompositePrimaryKey('business_id', 'region_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'business_shipping_regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessSuppliers',
            fields=[
                ('pk', models.CompositePrimaryKey('business_id', 'supplier_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'business_suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessTypeMap',
            fields=[
                ('pk', models.CompositePrimaryKey('business_id', 'type_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'business_type_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessTypes',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'business_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceAgreements',
            fields=[
                ('agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_number', models.TextField(blank=True, null=True)),
                ('articles_covered', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compliance_agreements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_year', models.IntegerField(blank=True, null=True)),
                ('check_number', models.CharField(blank=True, max_length=256, null=True)),
                ('license_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'licenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_number', models.CharField(blank=True, max_length=64, null=True)),
                ('mo_code', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=32, null=True)),
                ('county', models.CharField(blank=True, max_length=128, null=True)),
                ('gps_coordinates', models.TextField(blank=True, null=True)),
                ('field_location_notes', models.TextField(blank=True, null=True)),
                ('barriers_to_inspection', models.TextField(blank=True, null=True)),
                ('site_contact_name', models.CharField(blank=True, max_length=256, null=True)),
                ('site_contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('site_contact_email', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pests',
            fields=[
                ('pest_id', models.AutoField(primary_key=True, serialize=False)),
                ('pest_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'pests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlantTypes',
            fields=[
                ('plant_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'plant_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellingSeasons',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'selling_seasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingRegions',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'shipping_regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
    ]
