# Generated by Django 5.2.7 on 2025-11-23 06:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypes',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Business Type',
                'db_table': 'business_types',
            },
        ),
        migrations.CreateModel(
            name='Pests',
            fields=[
                ('pest_id', models.AutoField(primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=255, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pest_type', models.CharField(blank=True, choices=[('Insect', 'Insect'), ('Disease', 'Disease'), ('Fungus', 'Fungus'), ('Mite', 'Mite'), ('Weed', 'Weed'), ('Other', 'Other')], max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pests',
                'db_table': 'pests',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='PlantTypes',
            fields=[
                ('plant_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Plant Type',
                'db_table': 'plant_types',
            },
        ),
        migrations.CreateModel(
            name='SellingSeasons',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Selling Season',
                'db_table': 'selling_seasons',
            },
        ),
        migrations.CreateModel(
            name='ShippingRegions',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Shipping Region',
                'db_table': 'shipping_regions',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('Dealer', 'Dealer'), ('Nursery', 'Nursery')], max_length=20)),
                ('business_name', models.CharField(max_length=255, unique=True)),
                ('dba_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_address', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_city', models.CharField(blank=True, max_length=100, null=True)),
                ('mo_state', models.CharField(blank=True, max_length=2, null=True)),
                ('mo_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('main_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('main_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('main_contact_alt_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('main_contact_fax', models.CharField(blank=True, max_length=30, null=True)),
                ('main_contact_alt_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('class_code', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], db_column='class', max_length=1, null=True)),
                ('acreage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priority_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('is_interstate_shipper', models.BooleanField(default=False)),
                ('wants_email_renewal', models.BooleanField(default=False)),
                ('wants_email_license', models.BooleanField(default=False)),
                ('wants_labels', models.BooleanField(default=False)),
                ('num_labels', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('date_applied', models.DateField(default=django.utils.timezone.now)),
                ('formerly_known_as', models.CharField(blank=True, max_length=255, null=True)),
                ('business_types', models.ManyToManyField(blank=True, db_table='business_type_map', to='main.businesstypes')),
                ('plant_types', models.ManyToManyField(blank=True, db_table='business_plant_types', to='main.planttypes')),
                ('selling_seasons', models.ManyToManyField(blank=True, db_table='business_selling_seasons', to='main.sellingseasons')),
                ('shipping_regions', models.ManyToManyField(blank=True, db_table='business_shipping_regions', to='main.shippingregions')),
                ('suppliers', models.ManyToManyField(blank=True, db_table='business_suppliers', to='main.suppliers')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='ComplianceAgreements',
            fields=[
                ('agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_number', models.CharField(max_length=100, unique=True)),
                ('articles_covered', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.businesses')),
            ],
            options={
                'verbose_name_plural': 'Compliance Agreements',
                'db_table': 'compliance_agreements',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('legacy_license_id', models.CharField(blank=True, max_length=100, null=True)),
                ('store_number', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_coordinates', models.TextField(blank=True, null=True)),
                ('field_location_notes', models.TextField(blank=True, null=True)),
                ('barriers_to_inspection', models.TextField(blank=True, null=True)),
                ('site_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('site_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main.businesses')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('inspection_id', models.AutoField(primary_key=True, serialize=False)),
                ('inspected_by', models.CharField(blank=True, max_length=255, null=True)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('additional_inspection_date', models.DateField(blank=True, null=True)),
                ('passes_inspection', models.BooleanField(default=True)),
                ('verbal_report', models.BooleanField(default=False)),
                ('infestation_summary', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('samples_taken_pram', models.BooleanField(default=False)),
                ('sample_number', models.CharField(blank=True, max_length=256, null=True)),
                ('trace_back', models.TextField(blank=True, null=True)),
                ('trace_forward', models.TextField(blank=True, null=True)),
                ('scn_samples', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.locations')),
            ],
            options={
                'verbose_name_plural': 'Inspections',
                'db_table': 'inspections',
            },
        ),
        migrations.CreateModel(
            name='InspectionFindings',
            fields=[
                ('finding_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_description', models.CharField(blank=True, max_length=255, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='main.inspections')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.pests')),
            ],
            options={
                'verbose_name_plural': 'Inspection Findings',
                'db_table': 'inspection_findings',
            },
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_period_start', models.DateField()),
                ('license_period_end', models.DateField()),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.locations')),
            ],
            options={
                'verbose_name_plural': 'Licenses',
                'db_table': 'licenses',
                'unique_together': {('location', 'license_period_start')},
            },
        ),
    ]
