# Generated by Django 5.2.7 on 2025-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='mo_code',
            field=models.CharField(default=4, max_length=64),
            preserve_default=False,
        ),
    ]
