# Generated by Django 5.2.7 on 2025-11-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingregions',
            options={'managed': True},
        ),
    ]
