# Generated by Django 5.2.7 on 2025-11-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shippingregions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingregions',
            options={'managed': False},
        ),
    ]
