# Generated by Django 5.2.7 on 2025-12-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_merge_0002_locations_mo_code_0004_emailtemplate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingregions",
            options={"verbose_name": "Shipping Region"},
        ),
    ]
