# Generated by Django 5.2.7 on 2025-12-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_shippingregions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('nursery', 'Nursery'), ('dealer', 'Dealer')], max_length=32)),
                ('pdf', models.FileField(upload_to='renewal_templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
