# Generated by Django 5.2.7 on 2025-12-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_renewaltemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewaltemplate',
            name='pdf',
            field=models.FileField(upload_to='plant_license/pdfs/'),
        ),
    ]
