# Generated by Django 5.2.7 on 2025-12-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_renewaltemplate_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewaltemplate',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Stores the original filename for downloads', max_length=255),
        ),
    ]
