# Generated by Django 5.2.7 on 2025-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_renewaltemplate_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewaltemplate',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
