# Generated by Django 5.2.7 on 2025-12-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_locations_mo_code'),
        ('main', '0004_emailtemplate'),
    ]

    operations = [
    ]
